In [29]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

# Load the data
url="https://raw.githubusercontent.com/chiharuishida/Tutorialdata/main/Boston2.csv"
Boston = pd.read_csv(url)

In [30]:
Boston

,Unnamed: 0,crim,zone,industry,River,nitricoxidesconcentration,rooms,Proportionbefore1940,distanceto5bostonemployments,radialhighways,propertytax,pupil_teacher_ratio,proportion_low_status_in_population,medianvalue
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,7.88,11.9

In [31]:
#print summary statistics
print (Boston.describe())

       Unnamed: 0        crim        zone    industry       River  \
count  506.000000  506.000000  506.000000  506.000000  506.000000
mean   253.500000    3.613524   11.363636   11.136779    0.069170
std    146.213884    8.601545   23.322453    6.860353    0.253994
min      1.000000    0.006320    0.000000    0.460000    0.000000
25%    127.250000    0.082045    0.000000    5.190000    0.000000
50%    253.500000    0.256510    0.000000    9.690000    0.000000
75%    379.750000    3.677083   12.500000   18.100000    0.000000
max    506.000000   88.976200  100.000000   27.740000    1.000000

       nitricoxidesconcentration       rooms  Proportionbefore1940  \
count                 506.000000  506.000000            506.000000
mean                    0.554695    6.284634             68.574901
std                     0.115878    0.702617             28.148861
min                     0.385000    3.561000              2.900000
25%                     0.449000    5.885500             45.025000
50%                     0.538000    6.208500             77.500000
75%                     0.624000    6.623500             94.075000
max                     0.871000    8.780000            100.000000

       distanceto5bostonemployments  radialhighways  propertytax  \
count                    506.000000      506.000000   506.000000
mean                       3.795043        9.549407   408.237154
std                        2.105710        8.707259   168.537116
min                        1.129600        1.000000   187.000000
25%                        2.100175        4.000000   279.000000
50%                        3.207450        5.000000   330.000000
75%                        5.188425       24.000000   666.000000
max                       12.126500       24.000000   711.000000

       pupil_teacher_ratio  proportion_low_status_in_population  medianvalue
count           506.000000                           506.000000   506.000000
mean             18.455534                            12.653063    22.532806
std               2.164946                             7.141062     9.197104
min              12.600000                             1.730000     5.000000
25%              17.400000                             6.950000    17.025000
50%              19.050000                            11.360000    21.200000
75%              20.200000                            16.955000    25.000000
max              22.000000                            37.970000    50.000000

In [34]:
# =============================================================================
# In the Boston dataset, the first column did not have a header (hence 'Unnamed: 0')
# #Note: axis=1 indicates columns. axis=0 indicates index (roughly the same as rows)
# # we are using X to refer to predictor vairables, and Y to Target. Here we are including all
# #columns/variables besides the 'unnamed' and 'medv'
# =============================================================================

x = Boston.drop(['Unnamed: 0', 'medianvalue'], axis=1)
y = Boston['medianvalue']

#alternative way of writing the X is:
#x = dataset[['var1','var2','var3','var4']]
#the drop function is good to know as well if you are entering lots of X variables
#and just a couple excluded from the model. That way you don't have to write all the variable names

In [35]:
# importing the model
regressor = LinearRegression()

model = sm.OLS(y, x).fit()
## Inspect the results
print(model.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:            medianvalue   R-squared (uncentered):                   0.957
Model:                            OLS   Adj. R-squared (uncentered):              0.956
Method:                 Least Squares   F-statistic:                              908.7
Date:                Sun, 06 Nov 2022   Prob (F-statistic):                        0.00
Time:                        16:54:04   Log-Likelihood:                         -1539.0
No. Observations:                 506   AIC:                                      3102.
Df Residuals:                     494   BIC:                                      3153.
Df Model:                          12
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
crim                                   -0.1126      0.035     -3.194      0.001      -0.182      -0.043
zone                                    0.0502      0.015      3.388      0.001       0.021       0.079
industry                               -0.0226      0.066     -0.340      0.734      -0.153       0.108
River                                   3.1635      0.929      3.406      0.001       1.339       4.988
nitricoxidesconcentration              -0.9158      3.439     -0.266      0.790      -7.672       5.840
rooms                                   6.1869      0.315     19.669      0.000       5.569       6.805
Proportionbefore1940                   -0.0041      0.014     -0.291      0.771      -0.032       0.024
distanceto5bostonemployments           -0.8696      0.201     -4.336      0.000      -1.264      -0.476
radialhighways                          0.1086      0.068      1.604      0.109      -0.024       0.242
propertytax                            -0.0093      0.004     -2.297      0.022      -0.017      -0.001
pupil_teacher_ratio                    -0.2268      0.109     -2.084      0.038      -0.441      -0.013
proportion_low_status_in_population    -0.4372      0.052     -8.384      0.000      -0.540      -0.335
==============================================================================
Omnibus:                      195.875   Durbin-Watson:                   0.982
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1263.461
Skew:                           1.547   Prob(JB):                    4.39e-275
Kurtosis:                      10.096   Cond. No.                     6.77e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 6.77e+03. This might indicate that there are
strong multicollinearity or other numerical problems.